## new

In [1]:
import pandas as pd

# Load datasets
us = pd.read_csv("/Users/ghadena/Desktop/geopol/data/raw/us_df.csv")
german = pd.read_parquet("/Users/ghadena/Desktop/geopol/data/raw/urls.parquet")
french = pd.read_parquet("/Users/ghadena/Desktop/geopol/data/raw/french_election_texts.parquet")
entities = pd.read_csv("/Users/ghadena/Desktop/geopol/data/processed/entites_n_relationships.csv")

# Add source tags
us['source'] = 'us'
german['source'] = 'german'
french['source'] = 'french'

# --- Step 1: US relevance flag ---
us['is_relevant'] = (us['relevance_text'] == 1).astype("Int64") 
# Rename text column
if 'text' in us.columns:
    us.rename(columns={'text': 'article_text'}, inplace=True)
us.drop(columns=[
    'is_us_election', 'is_french_election', 'is_german_election',
    'relevance_text', 'relevance_description', 'text', 'Unnamed: 0'
], inplace=True, errors='ignore')

# --- Step 2: Create relevance lookup from entities ---
relevance_lookup = entities[['url', 'relevant_to_german_or_french_elections']].copy()

# Clean and convert to boolean: "true" → 1, everything else → 0
# Step 2: Clean and convert to 0 / 1 / NaN
relevance_lookup['is_relevant'] = (
    relevance_lookup['relevant_to_german_or_french_elections']
    .astype(str)
    .str.strip()
    .str.lower()
    .map(lambda x: 1 if x == 'true' else (0 if x == 'false' else pd.NA))
).astype("Int64") 

# Keep only what we need
relevance_lookup = relevance_lookup[['url', 'is_relevant']]

# --- Step 3: Merge into German & French ---
german = german.merge(relevance_lookup, on='url', how='left')
french = french.merge(relevance_lookup, on='url', how='left')

# Do NOT fill nulls — let is_relevant be NaN if URL not in entities

# --- Step 4: Combine all articles ---
texts = pd.concat([us, french, german], ignore_index=True)

In [2]:
texts.is_relevant.value_counts(normalize=True)

is_relevant
0    0.821051
1    0.178949
Name: proportion, dtype: Float64

In [37]:
# --- 10. Check % relevant articles by source ---
relevance_by_source = (
    texts.groupby('source')['is_relevant']
    .mean()
    .mul(100)
    .round(2)
    .rename('% Relevant')
)
print("📊 % Relevant articles by source:")
print(relevance_by_source)

# --- 11. Check missing article_text (NaN or empty) ---
missing_text = texts[
    texts['article_text'].isna() |
    (texts['article_text'].astype(str).str.strip() == '')
]
print(f"\n🛑 Articles with empty text: {len(missing_text)}")

📊 % Relevant articles by source:
source
french    15.92
german     9.86
us        26.15
Name: % Relevant, dtype: Float64

🛑 Articles with empty text: 1404

In [3]:
texts.shape

(6587, 7)

In [43]:
print("US columns:", us.columns)
print("German columns:", german.columns)
print("French columns:", french.columns)

US columns: Index(['url', 'datetime', 'language', 'description', 'article_text', 'source',
       'is_relevant'],
      dtype='object')
German columns: Index(['url', 'datetime', 'language', 'description', 'article_text', 'source',
       'is_relevant'],
      dtype='object')
French columns: Index(['url', 'datetime', 'language', 'description', 'article_text', 'source',
       'is_relevant'],
      dtype='object')

In [4]:
null_articles = texts[
    texts['article_text'].isna() |
    (texts['article_text'].astype(str).str.strip() == '')
]
null_articles

,url,datetime,language,description,article_text,source,is_relevant
3,https://www.nytimes.com/video,2025-04-21,en,"Last December, video emerged showing the bodie...",NaN,us,0
32,https://www.cnn.com/2024/09/06/europe/video-ru...,2024-09-06,en,"The troops stagger onto a dusty track, then on...",NaN,us,0
123,https://www.reuters.com/world/europe/books-scr...,2024-09-10,en,"This autumn, pupils in the Finnish town of Rii...",NaN,us,0
264,https://www.npr.org/2024/09/19/g-s1-23689/insi...,2024-09-19,en,"As they fought to keep Sean ""Diddy"" Combs out ...",NaN,us,0
274,https://www.bbc.com/news/articles/cz04m913m49o,2024-09-20,en,Details about the walkie-talkies detonated in ...,NaN,us,0
...,...,...,...,...,...,...,...
6582,https://www.france24.com/en/live-news/20250420...,2025-04-20T00:00:00.0000000,en,Holger Rune beat world number two Carlos Alcar...,,german,0
6583,https://www.france24.com/en/live-news/20250411...,2025-04-11T00:00:00.0000000,en,Chinese President Xi Jinping urged the Europea...,,german,0
6584,https://www.france24.com/en/tv-shows/business/...,2025-04-16T00:00:00.0000000,en,Emboldened by the latest economic data that sh...,,german,0
6585,https://www.france24.com/en/tv-shows/down-to-e...,2025-04-07T00:00:00.0000000,en,Wildlife trafficking is one of the most profit...,,german,0
6586,https://www.france24.com/en/live-news/20250416...,2025-04-16T00:00:00.0000000,en,US Secretary of State Marco Rubio was in Paris...,,german,0

In [5]:
null_counts_by_source = null_articles['source'].value_counts()
print(null_counts_by_source)

source
french    1008
german     364
us          32
Name: count, dtype: int64

In [60]:
# Check if this URL had article_text in original german
sample_url = null_articles.iloc[4]['url']
print("us original:")
print(us[us['url'] == sample_url][['url', 'article_text']])

us original:
                                                url article_text
274  https://www.bbc.com/news/articles/cz04m913m49o          NaN

In [61]:
null_articles.is_relevant.value_counts()

is_relevant
0    995
1    102
Name: count, dtype: Int64

In [63]:
# Flag articles where article_text is missing or empty
texts['used_description_as_text'] = (
    texts['article_text'].isna() |
    (texts['article_text'].astype(str).str.strip() == '')
).astype(int)

In [64]:
# Check how many and what sources have missing relevance info
is_relevant_nulls = texts[texts['is_relevant'].isna()]
print(f"🔍 Articles with null is_relevant: {len(is_relevant_nulls)}")

# Count by source
print("By source:")
print(is_relevant_nulls['source'].value_counts())

# Preview
is_relevant_nulls[['url', 'source', 'language', 'article_text', 'description']].head()

🔍 Articles with null is_relevant: 535
By source:
source
french    443
german     92
Name: count, dtype: int64

,url,source,language,article_text,description
3763,https://www.reuters.com/business/tariffs/,french,en,,Reuters.com is your online source for the late...
3764,https://www.reuters.com/world/russia-united-st...,french,en,,The United States and Russia both said on Thur...
3765,https://www.reuters.com/business/media-telecom...,french,en,,Item 1 of 6 Director Richard Linklater attends...
3766,https://www.reuters.com/world/europe/russia-us...,french,en,,"WASHINGTON/MOSCOW/KYIV, March 25 (Reuters) - T..."
3767,https://www.reuters.com/markets/europe/ukraine...,french,en,,Ukrainian service personnel use searchlights a...

In [70]:
is_relevant_nulls.sample(5).description.to_list()

['His comments come as Merkel, who led Germany between 2005 and 2021, re-enters the political fray. In a rare intervention, Merkel criticized Christian Democratic Union (CDU) leader Friedrich Merz for breaking the party’s long-standing firewall against the AfD by allowing far-right votes to help pass an anti-immigration motion in the Bundestag.. The nonbinding motion called for the rejection ...',
 'The Associated Press is an independent global news organization dedicated to factual reporting. Founded in 1846, AP today remains the most trusted source of fast, accurate, unbiased news in all formats and the essential provider of the technology and services vital to the news business.',
 'Shortly before the second round, Romania’s Constitutional Court ruled that the first round of voting had been so badly tainted by a Russian influence operation on social media that the entire process had to be scrapped and started over.. Iohannis was allowed to remain in office until the rerun of the presidential election, which is scheduled to begin on May 4.',
 "Water Matters. Europe's water is under increasing pressure. Pollution, droughts, floods are taking their toll on our drinking water, lakes, rivers and coastlines.",
 'Tigers vs. Blue Jays Prediction. Score Prediction: Tigers 5, Blue Jays 4 Total Prediction: Under 8.5 runs Tigers and Blue Jays Betting Trends. The Tigers have compiled a 20-5 record in games they were listed as the moneyline favorite (winning 80% of those games).']

In [ ]:
is_relevant_nulls.to_csv("redo2.csv") ## to do tmr

# droped is relevant nulls - merge back later

In [6]:
allowed_langs = ['en', 'de', 'fr']
texts = texts[texts['language'].isin(allowed_langs)].reset_index(drop=True)

In [7]:
texts = texts[texts['is_relevant'].notna()].reset_index(drop=True)

In [8]:
texts.shape

(6050, 7)

# merge w entites

In [9]:
# Load entities if not already in memory
entities = pd.read_csv("/Users/ghadena/Desktop/geopol/data/processed/entites_n_relationships.csv")

# Drop any duplicate URLs in entities (just to be safe)
entities = entities.drop_duplicates(subset='url')

# Merge texts with entities on 'url'
merged = texts.merge(entities, on='url', how='left', indicator=True)

In [16]:
entities.relevant_to_german_or_french_elections.value_counts()
entities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6250 entries, 0 to 6249
Data columns (total 6 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Unnamed: 0                              6250 non-null   int64
 1   url                                     6250 non-null   object
 2   lang                                    3981 non-null   object
 3   extracted_entities                      6250 non-null   object
 4   entity_relationships                    6250 non-null   object
 5   relevant_to_german_or_french_elections  3527 non-null   object
dtypes: int64(1), object(5)
memory usage: 293.1+ KB

In [198]:
merged["datetime"] = merged["datetime"].apply(
    lambda x: pd.to_datetime(x, errors='coerce') if pd.notna(x) else pd.NaT
)

In [199]:
merged.datetime

0      2024-09-12
1      2024-09-09
2      2024-09-11
3      2025-04-21
4      2024-09-09
          ...
6045   2025-04-20
6046   2025-04-11
6047   2025-04-16
6048   2025-04-07
6049   2025-04-16
Name: datetime, Length: 6050, dtype: datetime64[ns]

In [200]:
# Check how many articles didn't get matched
unmatched = merged[merged['_merge'] == 'left_only']
print(f"🟡 Unmatched articles: {len(unmatched)}")

🟡 Unmatched articles: 47

In [201]:
import pandas as pd
import json

# 1. Drop unmatched rows (only keep rows that were matched during merge)
merged = merged[merged['_merge'] == 'both'].reset_index(drop=True)

# 2. Drop unneeded columns
merged.drop(columns=[
    'Unnamed: 0', 'lang', 'relevant_to_german_or_french_elections', '_merge'
], inplace=True, errors='ignore')

In [202]:
# 3. Add flags: has_entities and has_relationships
import json
import ast

def is_non_empty_entity_dict(value):
    try:
        data = ast.literal_eval(value) if isinstance(value, str) else value
        if isinstance(data, dict):
            return any(len(v) > 0 for v in data.values())
        return False
    except (ValueError, SyntaxError):
        return False

def is_non_empty_relationship_list(value):
    try:
        data = ast.literal_eval(value) if isinstance(value, str) else value
        return isinstance(data, list) and len(data) > 0
    except (ValueError, SyntaxError):
        return False

# Apply to your merged DataFrame
merged['has_entities'] = merged['extracted_entities'].apply(is_non_empty_entity_dict).astype(int)
merged['has_relationships'] = merged['entity_relationships'].apply(is_non_empty_relationship_list).astype(int)

In [203]:
import ast

def has_key_in_literal_dict(field, key):
    try:
        obj = ast.literal_eval(field) if isinstance(field, str) else field
        return int(bool(obj.get(key)))
    except (ValueError, SyntaxError, TypeError):
        return 0
    
merged['has_people'] = merged['extracted_entities'].apply(lambda x: has_key_in_literal_dict(x, 'people'))
merged['has_organizations'] = merged['extracted_entities'].apply(lambda x: has_key_in_literal_dict(x, 'institutions'))

In [204]:
merged

,url,datetime,language,description,article_text,source,is_relevant,used_description_as_text,extracted_entities,entity_relationships,has_entities,has_relationships,has_people,has_organizations
0,https://www.washingtonpost.com/politics/intera...,2024-09-10,en,A: Trump believes human activity is just one c...,Q: Do you believe that climate change is large...,us,1,0,"{'people': ['Trump'], 'institutions': ['The Wa...","[{'source': 'Trump', 'target': 'climate change...",1,1,1,1
1,https://www.washingtonpost.com/politics/2024/0...,2024-09-09,en,"The page lists Harris’s economic, immigration ...",Vice President Kamala Harris’s campaign posted...,us,1,0,"{'people': ['Kamala Harris', 'Donald Trump', '...","[{'source': 'Kamala Harris', 'target': 'Donald...",1,1,1,1
2,https://www.washingtonpost.com/politics/intera...,2024-09-10,en,A: Harris wants to strengthen Social Security ...,Q: Do you believe that climate change is large...,us,1,0,"{'people': ['Harris'], 'institutions': ['Unite...","[{'source': 'Harris', 'target': 'climate chang...",1,1,1,1
3,https://www.washingtonpost.com/politics/2024/0...,2024-09-11,en,"Republicans in Winnemucca, Nev., gather at a w...",So just how emphatic was her win? And what do ...,us,1,0,"{'people': ['Harris', 'Trump', 'Joe Biden', 'H...","[{'source': 'Joe Biden', 'target': 'Trump', 'r...",1,1,1,1
4,https://www.washingtonpost.com/politics/intera...,2024-09-10,en,"Kamala Harris’s immigration policies, explaine...",Deporting undocumented people Q: Should all u...,us,1,0,"{'people': ['Harris', 'Donald Trump', 'Biden']...","[{'source': 'Harris', 'target': 'Donald Trump'...",1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5998,https://www.france24.com/en/live-news/20250420...,2025-04-20,en,Holger Rune beat world number two Carlos Alcar...,,german,0,1,"{'people': ['Holger Rune', 'Carlos Alcaraz'], ...",[],1,0,1,0
5999,https://www.france24.com/en/live-news/20250411...,2025-04-11,en,Chinese President Xi Jinping urged the Europea...,,german,0,1,"{'people': ['Xi Jinping', 'Donald Trump'], 'in...","[{'source': 'Xi Jinping', 'target': 'European ...",1,1,1,1
6000,https://www.france24.com/en/tv-shows/business/...,2025-04-16,en,Emboldened by the latest economic data that sh...,,german,0,1,"{'people': [], 'institutions': [], 'political_...",[],1,0,0,0
6001,https://www.france24.com/en/tv-shows/down-to-e...,2025-04-07,en,Wildlife trafficking is one of the most profit...,,german,0,1,"{'people': [], 'institutions': [], 'political_...",[],0,0,0,0
6002,https://www.france24.com/en/live-news/20250416...,2025-04-16,en,US Secretary of State Marco Rubio was in Paris...,,german,0,1,"{'people': ['Marco Rubio', 'Emmanuel Macron'],...","[{'source': 'Marco Rubio', 'target': 'Emmanuel...",1,1,1,1

In [205]:
both = merged[(merged['has_entities'] == 1) & (merged['has_relationships'] == 1)]
only_entities = merged[(merged['has_entities'] == 1) & (merged['has_relationships'] == 0)]
only_relationships = merged[(merged['has_entities'] == 0) & (merged['has_relationships'] == 1)]
neither = merged[(merged['has_entities'] == 0) & (merged['has_relationships'] == 0)]

print("🧾 Article extraction summary:")
print(f"🟢 Both entities & relationships: {len(both)}")
print(f"🟡 Only entities: {len(only_entities)}")
print(f"🔵 Only relationships: {len(only_relationships)}")
print(f"🔴 Neither: {len(neither)}")

🧾 Article extraction summary:
🟢 Both entities & relationships: 4180
🟡 Only entities: 1519
🔵 Only relationships: 0
🔴 Neither: 304

In [206]:
print("\n🧠 Breakdown of specific entity types:")
print("People:", merged['has_people'].sum())
print("Organizations:", merged['has_organizations'].sum())

🧠 Breakdown of specific entity types:
People: 4400
Organizations: 4912

# FE

In [207]:
import nltk
nltk.download('punkt', download_dir='/Users/ghadena/nltk_data/tokenizers/punkt')
nltk.data.path.append('/Users/ghadena/nltk_data/tokenizers/punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/ghadena/nltk_data/tokenizers/punkt...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/ghadena/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/ghadena/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [208]:
import pandas as pd
import numpy as np
import re
from urllib.parse import urlparse
from datetime import datetime
from nltk import pos_tag

# Use regex tokenizer to avoid punkt issues
def tokenize(text):
    return re.findall(r'\b\w+\b', text)

def count_verbs(text):
    if not isinstance(text, str) or not text.strip():
        return 0
    try:
        tokens = tokenize(text)
        tags = pos_tag(tokens)
        return sum(1 for _, tag in tags if tag.startswith("VB"))  # VB, VBD, VBG, etc.
    except Exception:
        return 0

# def get_article_type(text):
#     if not isinstance(text, str): return "other"
#     intro = text[:200].lower()
#     if "analysis" in intro:
#         return "analysis"
#     if "interview with" in intro or intro.startswith("interview:"):
#         return "interview"
#     return "other"

def generate_article_features(
    df,
    text_col="article_text",
    url_col="url",
    date_col="datetime"
):
    df = df.copy()

    # --- Ensure datetime format
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce", utc = False)

    # --- News org name from URL
    df["news_org"] = df[url_col].apply(lambda x: urlparse(x).netloc if pd.notnull(x) else None)

    # --- Extract slug-style title from URL
    df["url_slug_title"] = df[url_col].apply(
    lambda url: (
        url.strip("/").split("/")[-2].replace("-", " ").title()
        if pd.notnull(url) and "cnn.com" in url and url.strip("/").endswith("index.html")
        else url.strip("/").split("/")[-1].replace("-", " ").title()
        if pd.notnull(url) else None)
    )

    # --- Date features
    df["date"] = df[date_col].dt.date
    df["day_of_week"] = df[date_col].dt.day_name()
    df["month"] = df[date_col].dt.month
    df["is_weekend"] = df[date_col].dt.weekday >= 5

    # --- Days until elections
    us_election_date = pd.to_datetime("2024-11-05")
    french_election_date = pd.to_datetime("2024-07-07")
    german_election_date = pd.to_datetime("2025-02-23")
    df["days_until_us_election"] = (us_election_date - df[date_col]).dt.days
    df["days_until_french_election"] = (french_election_date - df[date_col]).dt.days
    df["days_until_german_election"] = (german_election_date - df[date_col]).dt.days

    # --- Word count
    df["word_count"] = df[text_col].apply(lambda x: len(str(x).split()) if pd.notnull(x) else 0)

    # --- Sentence count (basic estimate using punctuation)
    df["sentence_count"] = df[text_col].apply(lambda x: len(re.findall(r'[.!?]', str(x))) if pd.notnull(x) else 0)

    # --- Avg sentence length
    df["avg_sentence_length"] = df.apply(
        lambda row: row["word_count"] / row["sentence_count"] if row["sentence_count"] > 0 else 0,
        axis=1
    )

    # --- Noun count
    df["noun_count"] = df[text_col].apply(
        lambda text: sum(1 for word, tag in pos_tag(tokenize(str(text))) if tag.startswith("NN")) if pd.notnull(text) else 0
    )

    # --- Verb count
    df["verb_count"] = df[text_col].apply(count_verbs)
    
    # --- 
    df["contains_question"] = df[text_col].str.contains(r"\?", na=False)
    df["quote_count"] = df[text_col].apply(lambda x: str(x).count('"') + str(x).count("“"))
    df["contains_number"] = df[text_col].str.contains(r"\d", na=False)
    df["capital_ratio"] = df[text_col].apply(
    lambda x: sum(w.isupper() for w in str(x).split()) / len(str(x).split()) if isinstance(x, str) and len(x.split()) > 0 else 0
)
    social_platforms = ["twitter", "facebook", "instagram", "tiktok", "youtube", "threads", "x.com"]

    df["mentions_social_media"] = df[text_col].apply(
    lambda x: any(p in str(x).lower() for p in social_platforms)
    )

    # # --- Language fallback
    # if "language" not in df.columns:
    #     df["language"] = "en"

    # # --- Article type classification (simple heuristic)
    # df["article_type"] = df[text_col].apply(get_article_type)

    return df

In [210]:
df_featurized = generate_article_features(merged)

In [236]:
# dropped 16 obs wo date - only 1 was relevant 
df_featurized = df_featurized[df_featurized["datetime"].notna()].reset_index(drop=True)

In [212]:
df_featurized.groupby("is_relevant")[["contains_question", "contains_number", "mentions_social_media"]].describe().T
#df_featurized.groupby("relevance_text")[["capital_ratio", "quote_count"]].describe().T

is_relevant                       0      1
contains_question     count    4931   1072
                      unique      2      2
                      top     False  False
                      freq     3860    671
contains_number       count    4931   1072
                      unique      2      2
                      top      True   True
                      freq     3109    856
mentions_social_media count    4931   1072
                      unique      2      2
                      top     False  False
                      freq     4651    981

In [213]:
# Count how many unique news sources there are
unique_publishers = df_featurized['news_org'].nunique()
print(f"Number of unique publishers: {unique_publishers}")
df_featurized.news_org.value_counts()

Number of unique publishers: 27

news_org
www.aljazeera.com         665
www.politico.eu           641
www.euronews.com          590
www.france24.com          483
www.bbc.com               422
www.reuters.com           383
www.nbcnews.com           254
www.npr.org               218
www.cnn.com               209
www.liberation.fr         170
www.tagesschau.de         170
www.sueddeutsche.de       170
www.faz.net               170
www.spiegel.de            170
www.lefigaro.fr           170
www.zeit.de               170
www.nytimes.com           170
www.bfmtv.com             169
www.rfi.fr                169
www.bild.de               169
www.lemonde.fr            168
www.washingtonpost.com     66
www.bloomberg.com          18
apnews.com                 12
observers.france24.com      4
france24.com                2
www.theguardian.com         1
Name: count, dtype: int64

In [214]:
df_featurized.groupby("news_org")["is_relevant"].mean().sort_values(ascending=False)

news_org
www.nbcnews.com           0.602362
www.washingtonpost.com    0.575758
www.npr.org               0.454128
www.bloomberg.com         0.388889
www.liberation.fr         0.358824
www.cnn.com               0.354067
www.lefigaro.fr           0.335294
www.nytimes.com           0.294118
www.bfmtv.com             0.254438
www.tagesschau.de         0.229412
www.sueddeutsche.de       0.217647
www.rfi.fr                0.183432
www.zeit.de               0.176471
www.bild.de               0.147929
www.lemonde.fr               0.125
www.politico.eu           0.107644
www.aljazeera.com         0.106767
www.euronews.com               0.1
www.spiegel.de                 0.1
www.france24.com          0.093168
www.bbc.com                0.07346
www.faz.net               0.047059
www.reuters.com           0.018277
france24.com                   0.0
www.theguardian.com            0.0
observers.france24.com         0.0
apnews.com                     0.0
Name: is_relevant, dtype: Float64

In [215]:
df_featurized.columns

Index(['url', 'datetime', 'language', 'description', 'article_text', 'source',
       'is_relevant', 'used_description_as_text', 'extracted_entities',
       'entity_relationships', 'has_entities', 'has_relationships',
       'has_people', 'has_organizations', 'news_org', 'url_slug_title', 'date',
       'day_of_week', 'month', 'is_weekend', 'days_until_us_election',
       'days_until_french_election', 'days_until_german_election',
       'word_count', 'sentence_count', 'avg_sentence_length', 'noun_count',
       'verb_count', 'contains_question', 'quote_count', 'contains_number',
       'capital_ratio', 'mentions_social_media', 'article_type'],
      dtype='object')

In [216]:
df_featurized.groupby("is_relevant")[["word_count", "sentence_count", "avg_sentence_length", "noun_count", "verb_count"]].describe().T

is_relevant                           0             1
word_count          count   4931.000000   1072.000000
                    mean     567.107686    730.545709
                    std     1432.375152   1004.196277
                    min        0.000000      0.000000
                    25%       24.000000    149.750000
                    50%      216.000000    474.500000
                    75%      528.000000   1018.000000
                    max    15378.000000  14489.000000
sentence_count      count   4931.000000   1072.000000
                    mean      30.346583     39.120336
                    std       81.524673     58.393490
                    min        0.000000      0.000000
                    25%        2.000000      7.000000
                    50%       11.000000     24.000000
                    75%       26.000000     52.000000
                    max     1019.000000    710.000000
avg_sentence_length count   4931.000000   1072.000000
                    mean      16.159655     18.605533
                    std       10.173588      9.866474
                    min        0.000000      0.000000
                    25%       11.120192     14.574178
                    50%       17.694444     19.184659
                    75%       22.818182     23.625866
                    max       84.000000    171.333333
noun_count          count   4931.000000   1072.000000
                    mean     307.530116    308.869403
                    std     1041.354574    489.934716
                    min        0.000000      0.000000
                    25%       16.000000     71.000000
                    50%       91.000000    220.500000
                    75%      230.500000    400.250000
                    max    11239.000000   9289.000000
verb_count          count   4931.000000   1072.000000
                    mean      73.057189    111.140858
                    std      136.017765    152.721333
                    min        0.000000      0.000000
                    25%        3.000000     14.000000
                    50%       28.000000     56.500000
                    75%       81.000000    163.250000
                    max     1447.000000   1601.000000

# election words

In [217]:
import re

def find_trigger_in_middle_body(row, keywords, cutoff_ratio=0.1):
    # Choose fallback if article_text is null or fallback flag is 1
    text = row['article_text']
    if pd.isna(text) or row.get('used_description_as_text', 0) == 1:
        text = row.get('description')

    if not isinstance(text, str):
        return None
    
    words = text.split()
    if len(words) < 5:
        return None

    start = int(len(words) * cutoff_ratio)
    end = int(len(words) * (1 - cutoff_ratio))
    middle_text = " ".join(words[start:end])
    
    for kw in keywords:
        if re.search(rf"\b{re.escape(kw)}\b", middle_text, flags=re.IGNORECASE):
            return kw
    return None

In [218]:

election_keywords = [
    "us election", "2024 election", "vote", "voting", "presidential campaign"
]

# Count number of matched election keywords in the article_text (or fallback)
df_featurized["election_keyword_count"] = df_featurized["article_text"].apply(
    lambda text: sum(
        bool(re.search(rf"\b{re.escape(kw)}\b", str(text), flags=re.IGNORECASE))
        for kw in election_keywords
    )
)

# Find if any keyword is mentioned in the middle of the text (with fallback support)
df_featurized["triggered_keyword"] = df_featurized.apply(
    lambda row: find_trigger_in_middle_body_rowwise(row, election_keywords),
    axis=1
)

# Flag if any keyword was found
df_featurized["mentions_election_keywords"] = df_featurized["triggered_keyword"].notna()

In [219]:
false_positives = df_featurized[
    (df_featurized["mentions_election_keywords"]) &
    (df_featurized["is_relevant"] == 0)
]

print(f"Election keyword false positives: {len(false_positives)}")


true_positives = df_featurized[
    (df_featurized["mentions_election_keywords"]) &
    (df_featurized["is_relevant"] == 1)
]

print(f"Election keyword true positives: {len(true_positives)}")
#true_positives[["article_text", "mentions_election_keywords", "is_relevant"]].head()

Election keyword false positives: 209
Election keyword true positives: 342

In [220]:
false_positives[["article_text", "mentions_election_keywords", "is_relevant", "triggered_keyword"]].head()
false_positives.iloc[1]["article_text"]

'Mexico\'s Senate just approved changing the constitution. Here\'s what you need to know  toggle caption Felix Marquez/AP  MEXICO CITY — Mexico’s Senate on Wednesday narrowly passed sweeping changes to the courts that include having judges elected by the public rather than appointed, in a major and controversial set of constitutional reforms.  The approval came hours after hundreds of protesters broke into Mexico\'s Senate, forcing the body to take a temporary recess. The proposed reforms have led judges and other judicial staff to strike and protest, in what’s become one of Mexico’s biggest constitutional debates in years.  Here are the main things to understand about the reforms and why they are so controversial.  Sponsor Message  The government vows to root out court corruption  For nearly a year, outgoing President Andrés Manuel López Obrador has been promoting a plan to remake the federal judiciary and Claudia Sheinbaum, the president-elect, due to take over in October, backs the reforms. Both accuse the courts of gross corruption and say their changes are crucial.  The biggest proposal changes how federal judges are selected. Instead of working their way up the judiciary, the governing party wants them to be elected by popular vote. Like presidents and lawmakers, the governing party reasoned, judges from the Supreme Court on down to local courts will have to run for office.  The plan also includes reforms like making sure no judicial worker makes more than the president.  toggle caption Rodrigo Oropeza/AFP via Getty Images  Mexico’s June elections handed Sheinbaum the victory and congressional supermajority needed to amend the Constitution.  López Obrador and his protege Sheinbaum say this will make the judiciary answer to the people instead of big business or organized crime.  After the lower house of Congress passed the reform 359-135, congressman Ricardo Monreal celebrated.  “We believe that we will end nepotism, corruption, influence peddling, the conflict of interest, the sale of justice to the highest bidder,” he said.  Sponsor Message  The judiciary is up in arms  Judges and judicial staff have been on strike since Aug. 19.  Last week, they formed picket lines in front of federal courthouses and just as the Mexican Congress was set to begin debating the measure, they surrounded the lower bodies’ headquarters in Mexico City to block the session.  World Mexico\'s federal judiciary goes on strike Mexico\'s federal judiciary goes on strike Listen · 2:19 2:19  “Democracy is in danger," José Fernando Migues Hernández, a Mexican judiciary worker, told NPR.  What’s more, federal courts had issued three injunctions in an attempt to stop the reforms.  But governing party lawmakers worked around the protesters and injunctions, saying they were an infringement of their constitutional rights, and they pressed on. Instead of meeting at Congress, they announced they would debate at a gym outside Mexico City. That’s where legislators from the lower house approved the raft of measures.  This has been tried before  Under its 1857 Constitution, Mexico actually used to elect its judges, according to Mónica Castillejos-Aragón, who clerked in Mexico\'s Supreme Court and now teaches comparative law at University of California, Berkeley.  When the framers of the current constitution, which was passed in 1917, discussed the judiciary they called electing judges an “inexplicable aberration.” They believed that elected judges led to corruption, so they reasoned that unlike the other two branches of government, the judiciary should be above politics.  “The framers expressed the need to establish an independent judicial power with security of tenure,” she says.  As the country took steps toward democracy in the 1990s, it also began appointing judges the way the United States does at the federal level. (Some U.S. states elect local judges.) And in the early 2000’s, nearly 80 years after it became independent on paper, the court finally began issuing landmark opinions.  “For the very first time in history, the Mexican judges were able to interpret and expand the scope of the rights already recognized in the Mexican Constitution,” Castillejos-Aragón says.  Sponsor Message  In recent years, the courts have struck down key policies of the president. For instance, in April 2023, the Supreme Court ruled that the National Guard — a large paramilitary force created by President López Obrador to patrol the country — could not remain under military command.  toggle caption Guillermo Arias/AFP via Getty Images  Castillejos-Aragón says the new reforms might put in danger hard-fought independence that allowed the judiciary to check the presidency. She believes the current leadership is reacting to decisions like that National Guard ruling: The executive, now armed with a supermajority, wants to make sweeping changes without the courts getting in its way.  The only big democracy to elect judges at the federal level by popular vote is Bolivia, says Julio Ríos, who studies judiciaries at the Autonomous Technological Institute of Mexico. According to Ríos, the Bolivian reform, instituted in 2009, did diversify the courts but it did not make them any less corrupt. He says it just politicized the courts and weakened the public’s confidence in them.  However, according to constitutional lawyer Juan Carlos González Cancino, Mexico’s changes are necessary.  He says the federal judiciary is corrupt. Big tax cases or business cases get decided with a phone call or a bag of money, he says. In his mind, this is not about democracy. It\'s about factions of the Mexican elite fighting for power and the money that power begets.  “But that ends because this reform destroys that power structure,” he says.  Ultimately, he says, it doesn’t matter what the courts think about these reforms. The Mexican people spoke loud and clear when they handed the government the supermajority needed to reform the Constitution.  “The function of the judiciary should be to defend the popular will, as manifested by the constitution,” he says.'

In [221]:
df_featurized.is_relevant.value_counts()

is_relevant
0    4931
1    1072
Name: count, dtype: Int64

# try 2 for keyword flag

In [222]:
# --- ENGLISH ---
english_keywords = {
    "election", "elections", "vote", "voting", "ballot", 
    "campaign", "candidate", "debate", "run for president"
}
english_figures = {
    "biden", "kamala", "harris", "trump", "pence", "obama", 
    "de santis", "haley", "kennedy", "bernie", "democrat", "republican"
}

# --- GERMAN ---
german_keywords = {
    "wahl", "wahlen", "abstimmung", "stimme", "abgeordnetenhaus", 
    "kanzler", "kandidaten", "wahlkampf", "bundestagswahl"
}
german_figures = {
    "scholz", "merkel", "laschet", "habeck", "baerbock", 
    "afd", "spd", "fdp", "grünen", "cdu", "csu"
}

# --- FRENCH ---
french_keywords = {
    "élection", "élections", "vote", "voter", "scrutin", 
    "candidat", "campagne", "présidentielle", "second tour"
}
french_figures = {
    "macron", "le pen", "mélenchon", "zemmour", "hidalgo", 
    "rn", "lrem", "ps", "républicains"
}

all_keywords = english_keywords | german_keywords | french_keywords
all_figures = english_figures | german_figures | french_figures

In [223]:
def compute_election_certainty(row, keywords, figures):
    text = row.get("article_text")
    
    # Fallback to description if article_text is missing
    if pd.isna(text) or row.get("used_description_as_text", 0) == 1:
        text = row.get("description")
    
    if not isinstance(text, str):
        return 0

    text_lower = text.lower()

    found_keywords = {kw for kw in keywords if re.search(rf"\b{re.escape(kw)}\b", text_lower)}
    found_figures = {pf for pf in figures if re.search(rf"\b{re.escape(pf)}\b", text_lower)}

    # High certainty if 2+ election keywords OR strong phrases
    if len(found_keywords) >= 2:
        return 2
    
    # Medium certainty if 1 keyword + a political figure mentioned
    if len(found_keywords) >= 1 and len(found_figures) >= 1:
        return 1

    # Otherwise, not election-related
    return 0

In [224]:
df_featurized['election_certainty'] = df_featurized.apply(
    lambda row: compute_election_certainty(row, all_keywords, all_figures),
    axis=1
)

In [225]:
print("🔍 Certainty counts:")
print(df_featurized['election_certainty'].value_counts())

# Breakdown
print("\n✅ High certainty:", (df_featurized['election_certainty'] == 2).sum())
print("⚠️ Medium certainty:", (df_featurized['election_certainty'] == 1).sum())
print("❌ Not election-related:", (df_featurized['election_certainty'] == 0).sum())

🔍 Certainty counts:
election_certainty
0    4792
2     841
1     370
Name: count, dtype: int64

✅ High certainty: 841
⚠️ Medium certainty: 370
❌ Not election-related: 4792

In [226]:
# High Certainty (2)
high = df_featurized[df_featurized['election_certainty'] == 2]
high_tp = high[high['is_relevant'] == 1]
high_fp = high[high['is_relevant'] == 0]

# Medium Certainty (1)
medium = df_featurized[df_featurized['election_certainty'] == 1]
medium_tp = medium[medium['is_relevant'] == 1]
medium_fp = medium[medium['is_relevant'] == 0]

# False Negatives: was relevant, but flagged as 0
fn = df_featurized[(df_featurized['election_certainty'] == 0) & (df_featurized['is_relevant'] == 1)]

# True Negatives: both are zero
tn = df_featurized[(df_featurized['election_certainty'] == 0) & (df_featurized['is_relevant'] == 0)]

In [227]:
print("📊 High Certainty")
print("✅ True Positives:", len(high_tp))
print("❌ False Positives:", len(high_fp))

print("\n📊 Medium Certainty")
print("✅ True Positives:", len(medium_tp))
print("❌ False Positives:", len(medium_fp))

print("\n📉 Missed Detections (False Negatives):", len(fn))
print("✅ True Negatives:", len(tn))

📊 High Certainty
✅ True Positives: 542
❌ False Positives: 299

📊 Medium Certainty
✅ True Positives: 185
❌ False Positives: 185

📉 Missed Detections (False Negatives): 345
✅ True Negatives: 4447

In [228]:
def precision(tp, fp):
    return tp / (tp + fp) if (tp + fp) > 0 else 0

def recall(tp, fn):
    return tp / (tp + fn) if (tp + fn) > 0 else 0

print("\n🎯 High Certainty Precision:", round(precision(len(high_tp), len(high_fp)), 2))
print("🎯 Medium Certainty Precision:", round(precision(len(medium_tp), len(medium_fp)), 2))

print("\n📈 Overall Recall:", round(recall(len(high_tp) + len(medium_tp), len(fn)), 2))

🎯 High Certainty Precision: 0.64
🎯 Medium Certainty Precision: 0.5

📈 Overall Recall: 0.68

We implemented a rule-based system to flag election-related content with high and medium certainty using multilingual keywords and political figure references. The high-certainty flags achieved a precision of 64%, meaning over a third of those articles were false positives, while the overall recall of 68% indicates that the rules missed about a third of truly relevant articles. These results suggest that while the rules are useful for capturing obvious election-related cases, they struggle with nuanced or indirect mentions—making them valuable but imperfect features for our downstream machine learning model, which can learn to generalize beyond these limitations.

# title

In [229]:
df_featurized.url_slug_title.to_list()

['Donald Trump Policy Positions',
 'Kamala Harris Campaign Platform Website',
 'Kamala Harris Policy Positions',
 'Kamala Harris Debate Performance Polls',
 'Kamala Harris Immigration',
 'Change Healthcare Letter Hack Data Breach',
 'Nexus Yuval Noah Harari Review',
 'Liane Moriarty Here One Moment',
 'Kamala Harris Abortion',
 'Elizabeth Strout Tell Me Everything Review',
 'Waymo Vs Uber Lyft Cost Speed Robotaxi Rideshare',
 'Playground Richard Powers Novel Review',
 'Ukraine Thermite Dragon Drones Intl Hnk Ml',
 'Debate Takeaways Trump Harris',
 'Nasa Boeing Starliner Capsule 09 06 24',
 'Trump Modify 25Th Amendment Harris Biden',
 'Trump Economic Plans Musk Government Commission',
 'Covid Vaccine Cost Pharmacies',
 'Boeing Starliner Return Without Astronauts',
 'Fact Check Debate Trump Harris',
 'Kamala Harris Donald Trump Debate',
 'Harris Trump Debate Analysis',
 'Fact Check Trump Vance Tariffs',
 'Rancho Palos Verdes Landslide Rainfall',
 'Rancho Palos Verdes California Landslide',
 'Nyfw Ss25 Highlights',
 'Energy Drinks Caffeine Dangers Wellness',
 'Child Care Trump What Matters',
 'Food Dye Transparent Mice Skin',
 'Changing Classrooms Shooting Safety Dg',
 'Colorado Apartment Complex Battleground Immigration',
 'Fact Check Presidential Debate Trump Harris Rcna169687',
 'Presidential Debate Takeaways Trump Harris Rcna169060',
 'Trump Pushes Baseless Claim Immigrants Eating Pets Rcna170537',
 'Father 11 Year Old Killed Ohio Crash Says Trump Vance Are Using Son Po Rcna170525',
 'Graphic Tracking Topics Mentioned Presidential Debate Rcna170270',
 '2 Teens 2 Teachers Killed Georgia School Shooting Leave Trail Grief Rcna169778',
 'Taylor Swift Endorses Kamala Harris Rcna170547',
 'Trump False Claims Schools Transgender Surgeries Rcna170217',
 'Russian Money Was Funneled Right Wing Creators Trump Media Outlet Pros Rcna169611',
 'Trump Vows Prosecute Political Foes Others Corrupt Cheaters Rcna169292',
 'Multiple Myeloma Symptoms Treatment Patti Scialfa Bruce Springsteen Rcna170269',
 'Georgia School Shooting Suspect Victims Apalachee What Know Rcna169700',
 'Donald Trump Plan Mandate Free Ivf Republicans Congress Opposition Rcna170327',
 'Boeing Spaceship What Went Wrong Nasa Astronauts Rcna167163',
 'Lifeline Distraction Shooting Reignites Debate Phones Schools Rcna169920',
 'Boeing Starliner Return No Astronauts Rcna169336',
 'Eagles Packers Game Nfl Live Updates Rcna169867',
 'Chase Bank Glitch Check Fraud Customers Reported To Authorities Rcna169986',
 '2 White Supremacists Tried Spark Race War Soliciting Murder Hate Crime Rcna170284',
 'What Are Best Skin Care Products Acne Prone Skin Look Ncna1032911',
 'Viktor Orban Hungary Donald Trump Presidential Debate',
 'Central Park Five Trump Debate',
 'Russia Election Influencers Youtube',
 'Fact Check Trump Harris Presidential Debate 2024',
 'Grocery Prices Inflation Corporate Greedflation',
 'Trump Harris Election Platforms Education Views',
 'Preventing School Shootings',
 'The Downfall Of Dei',
 'Inflation In America',
 'Regenerative Agriculture Climate Change Soil Carbon',
 'Laura Loomer Donald Trump Relationship Republicans Criticism',
 'My Brilliant Friend Lenu Lila Hbo Drama Final Season',
 'Abortion Roe Wade Ivf Donald Trump Kamala Harris Debate 2024',
 'Donald Trump Debate Eating Dogs Cats Immigrants False Stereotype',
 'Mexico Judicial Reform Elect Judges Constition Change',
 'Harris Campaign Abortion Reproductive Freedom Bus Tour Ivf Trump',
 'Elon Musk Ai Xai Supercomputer Memphis Pollution',
 'Inflation Consumer Prices Economy Interest Rates',
 'Consider This From Npr Draft 09 06 2024',
 'Indian Migrants Immigration Canada Northern Border Illegal Us Customs And Border Protection',
 'Cn9L9500Vg7O',
 'C2501N5Rvvno',
 'Credy50Z4J1O',
 'C74J2Lz88Pwo',
 'C20Rq73P3Z4O',
 'World Us Canada 35318432',
 'C4Gl323R1Y6O',
 'Cd9Dwxexp77O',
 'Cdjw0V3Zx4Ko?At_Bbc_Team=Editorial&At_Link_Origin=Bbcnorfolk&At_Ptr_Name=Twitter&At_Format=Link&At_Campaign_Type=Owned&At_Link_Id=3E0C0758 6Cdf 11Ef 8E5C 81D8Ab209D27&At_Link_Type=Web_Link',
 'Israel War On Gaza Live Israel Kills 31 In Gaza As 750000 March In Israel',
 'Russia Claims Kursk Counteroffensive Pushing Back Ukraine Forces',
 'In Tunisia Refugees And Migrants Are Expelled To The Desert Left Helpless',
 'Half The City Underwater One Million Affected By Northern Nigeria Floods',
 'What Was Netanyahus Map And Plan For Gaza All About',
 'What Are Dragon Drones Ukraines Latest Weapon Against Russia',
 'Algerias Abdelmadjid Tebboune Re Elected President With 94 7 Percent Vote',
 'What Was The Humanitarian Zone Bombed Overnight By Israel',
 'Why Is Germany Imposing More Restrictions On Its Borders',
 'Uncertainty Looms As Pakistan Awaits Imfs Approval Of 7Bn Bailout Package',
 'New Zealands Young Are Departing In Record Numbers As Cost Of Living Bites',
 'Protesters Rally In France Against Barniers Appointment As Pm',
 'After Edmundo Gonzalez Flees Whats Next For Venezuela And Its Opposition',
 'Why Are Cape Fur Seals In South Africa Getting Infected With Rabies',
 'Why African Countries Struggle To Produce Vaccines',
 'Russia Backs Kamala Harris Putins History Of Us Election Endorsements',
 'Hasina Gone But Fate Of Bangladeshs Forcibly Disappeared Hangs In Balance',
 'Cheneys Policies As Vp Caused Immense Human Suffering On A Global Scale',
 'A City At Risk Of Collapsing The Cost Of The Search For Gold In Zimbabwe',
 'The Paralympics Are Supposed To Be Fair And Inclusive But Often Fail To Be',
 'Cyberattacks Us Utilities Surged 70 This Year Says Check Point 2024 09 11',
 'China Deepen Industrial Agricultural Trade Investment Ties With Africa 2024 09 05',
 'Books Screens Out Some Finnish Pupils Go Back Paper After Tech Push 2024 09 10',
 'Whats Chinas Carbon Market How Does It Work 2024 09 12',
 'Russias Birth Rate Slides Lowest Quarter Century 2024 2024 09 10',
 'Nigeria Licenses First Floating Lng Plant Export Domestic Use 2024 09 06',
 'Us Government Shutdown What Closes What Stays Open 2024 09 11',
 'Video Trump Insulting Soldiers During Fox News Call Is Altered 2024 09 05',
 'Debate Trump Shares Falsehoods About Pet Eating Infanticide 2024 09 11',
 'Most Mass School Shootings Are Not Carried Out By Transgender People 2024 09 06',
 'Defining Images 911 Attacks 2024 09 10',
 'No Evidence Haitian Immigrants Stealing Eating Pets Ohio 2024 09 10',
 'Nmopagnqapa',
 'Mario Draghi Report Says Eu Must Spend Twice As Much After Wwii',
 'Germany De',
 'Europe Mario Draghi Report Unleashed Eurozone Debt Crisis Ecb Competition Investment',
 'Europe Defense Mario Draghi Arms Industry Guns Missiles Tanks Spending',
 'Europe Energy Bills Germany Brussels Pipeline Prices',
 'Mario Draghi Report Europe Finances Invest Energy Work',
 'Elon Musk Mario Draghi Report Eu Regulation Competitiveness Companies',
 'Ukraine Russian Oil Hungary Mol Lukoil Sanctions',
 'Mario Draghi Leurope Doit Investir Bce Eu Reformes',
 'Russia Polish Private University Scandal Pis Politics Cba',
 'Commission Scores Surprise Win In Apple Tax Row',
 'Slovenia New Commissioner Eu Nominee Marta Kos Female Candidate Ursula Von Der Leyen',
 'Draghis Report Game Changer Or Doorstop',
 'Great Commission Eu Council Parliament Ursula Von Der Leyen',
 'Josef Sikela Trade Portfolio European Commission Czech Republic Top Jobs',
 'Germany Border Control Donald Tusk Poland Security Irregular Migration',
 'Ukraine Appoints Andriy Sybiha New Foreign Minister Volodymyr Zelenskyy',
 'Fbi Dossier Reveals Russian Psy Ops Disinformation Campaign Election Europe',
 'Far Right Afd Radical Left Politics Russia Germany Europe',
 'Michael Mcgrath Eu Commission Ireland Von Der Leyen Brussels',
 'Draghis Report On Eu Competitiveness Five Key Takeaways',
 'We Never Let Them In Hungarys Pm Viktor Orban Demands New Laws Tackling Migration',
 'Germany Tightens Border Checks What Will Change For Travellers',
 'Why Is Germany Strengthening Its Border Controls Now',
 'Europes Fragmented Defence Industry Needs Coordination To Avoid Supply Crisis Draghi Repor',
 'Starved And Excommunicated What Is Happening To Belarusian Political Prisoner Maria Kalesn',
 'European Left Party Splits As New Group Eyes New Central And Eastern Countries',
 'Hungarian Families Say Area Risks Becoming A Battery Wasteland In Wake Of Chinese Lithium ',
 'Tesla Says Full Self Driving Car Expected In Europe Early Next Year Pending Regulatory App',
 'Ukraine Needs To Align Legal Framework With Eu Says New Justice Minister Olha Stefanishyna',
 'International Ai Treaty To Be Signed By Eu Uk And Us',
 'Why Are European Automakers Struggling In The Electric Vehicle Market',
 'Ireland Is Running A Budget Surplus Why Has It Been Warned To Stop Spending',
 'New Eu Travel Rules For Tourists What Changes In 2025',
 'Volvo Reverses Plan To Sell Only Electric Cars By 2030 As Demand Falls',
 'The Draghi Eu Competitiveness Report The Reactions',
 'With Ai Eu Has Opportunity To Capitalise On Digital Says Draghi',
 'Sanchez Urges The Eu To Reconsider Tariffs On Chinese Electric Cars Exposing Cracks',
 'A Big Win For The Eu How Californias Ai Legislation Compares To The Eu Ai Act',
 'Eu Scales Down Proposed Tariffs On Teslas And Other Chinese Evs',
 'Germany Confirms Inflation Rate At Lowest Level In More Than Three Years',
 'Hsbc Looks To Cut Costs Through Merger Of Major Divisions',
 'Some French Trains Have New Luggage Regulations Heres How To Avoid A Fine',
 'A Village In Swedish Lapland With A Dwindling Population Is Paying Families 900 To Move Th',
 'Germany Approves Bailout For Meyer Werft Shipbuilder Hit By Financial Woes',
 'Using Your Phone Abroad Should You Choose An E Sim Or Data Pass When Travelling In Europe',
 'Eu Construction Will Decline In 2024 But Is Set To Recover Next Year',
 'Polish Travel Group Esky Acquires Thomas Cook From Chinese Owner',
 'The New Era Of Travel Ai Robots And Regenerative Experiences',
 'France Spent 2Bn On The Olympics Was It Good For The Economy',
 'Best Nyt Cooking Recipes.Html',
 'Israel Exploding Pagers Hezbollah.Html',
 'Trump Violence Assassination Attempt.Html',
 'Inflammation Theory Of Disease.Html',
 'Defense Commissioner Military Ukraine Russia.Html',
 'Google Ad Antitrust Trial Arguments.Html',
 'The Substance Review.Html',
 'Flashback.Html',
 'Entitlement Rumaan Alam.Html',
 'Birds Migration Energy.Html',
 'Tupperware Bankruptcy.Html',
 'Yale Princeton Duke Asian Students Affirmative Action.Html',
 'Smic China Us Trade War.Html',
 'Alcohol Cancer Young Adults.Html',
 'Qualcomm Intel Talks Sale.Html',
 'Google Antitrust Youtube Ceo.Html',
 'Elon Musk Security.Html',
 'All Black Clothing.Html',
 'Tiktok Us Ban Court.Html',
 'Election Health Care Issue.Html',
 'Earth Temperature Global Warming Planet',
 'Energy Ai Use Electricity Water Data Centers',
 'Popular Names Republican Democrat',
 'Richard Osman We Solve Murders Review',
 '23Andme Board Turmoil Dna Test',
 'China Tariffs Biden Trump',
 'Department Of Education Shut Down Trump',
 'Titan Submersible Oceangate Implosion Update',
 'Lebanon Pager Attack Explosions Hezbollah Explainer Intl Latam',
 'Health Care Rankings High Income Nations Commonwealth Report',
 'Ryan Routh Trump What We Know Intl Hnk',
 'Elon Musk Richest Person Trillionaire',
 'Antibiotic Resistant Superbug Infections 2050 Wellness',
 'Huanan Animal Market Analysis Covid 19',
 'Teamsters Will Not Endorse Us President',
 'Right Wing Media Influencers Tenet Russian Money',
 'Blue Wall States Harris Trump Analysis',
 'Tupperware Files Bankruptcy',
 'Sean Diddy Combs Legal Allegations Timeline',
 'Mansion To Misery A Glimpse Inside The Prison Sean Diddy Combs Is Calling Home',
 'Glp 1 Pills Weight Loss Treatment',
 'Have I Got News For You Stars',
 'Deep Underwater Habitats Vanguard Sentinel Hnk Spc',
 'Mid Autumn Moon Festival Traditions',
 'Interest Rate Cut Federal Reserve Decision How Much Rcna171453',
 'Us Health Care Ranking Report Last Rcna171652',
 'Trump Degrading Language Immigrants Rcna171120',
 'Israel Hezbollah Pagers Explosions What Now Rcna171602',
 'Apocalypse Delayed Trump Promising Doom Never Comes Rcna170151',
 'Sean Diddy Combs Arrest Live Updates Rcna171438',
 'Tiktok Says Not Spreading Chinese Propaganda Us Says Real Risk Rcna171201',
 'Putin Orders Russian Army Expand War Ukraine Rcna171429',
 'Map New Data Shows Many Americans Are Without Homeowners Insurance Rcna169974',
 'Far Right Activist Laura Loomer Access Trump Crisis Campaign Rcna170915',
 'Social Media Companies Engaged Vast Surveillance Ftc Finds Calling Sta Rcna171814',
 'Emmys 2024 Complete Winners List Rcna171224',
 'Trump Crypto Event World Liberty Financial Rcna171407',
 'Teamsters Union Declines Endorse Presidential Election Breaking Decade Rcna171711',
 'University North Texas Corpses Dissected Unclaimed Bodies Rcna170478',
 'Florida Covid Shots Mrna Vaccines Older Adults Rcna170997',
 'House Republicans Vote Funding Bill Shutdown Trump Save Act Rcna171635',
 'Diddy Lawsuits Timeline Allegations What Know Rcna145335',
 'Florida 11 Year Old Arrested Sheriff Release Mugshot Rcna171437',
 'Donald Trump Jd Vance Relationship Rcna171181',
 'Scranton Munitions Factory Ukraine War Russia Howitzer Rounds',
 'Murdoch Family Trust Fox News Succession',
 'Breaking Down Former President Donald Trumps Rambling Linguistic Style',
 'Lucky Loser Dispels The Myth Of Trump As A Self Made Billionaire',
 'Trump Shooting Assassination Attempt Suspect Ryan Wesley Routh',
 'Political Violence Trump',
 'Federal Reserve Interest Rate Cut Inflation',
 'What If We Get It Right Experts Talk About Addressing Climate Crisis In New Book',
 'Boeing Strike Union Machinists Contract Labor',
 'Chemicals From Food Packaging Leach Into Food Affecting Peoples Health',
 'Overdose Fatal Fentanyl Death Opioid',
 'Emmy Awards 2024 Winners Tv Awards',
 'Money Happiness Kahneman Killingsworth',
 'China Retirement Age',
 'Employee Praise Recognition Retention Gallup',
 'Shein Temu White House Biden Rule China',
 'Federal Reserve Rate Cut Housing Home Prices Mortgages',
 'Americans Passport Renew Online',
 'The Latest On The Land Back Movement In Which Native American Tribes Reclaim Land',
 'Instagram Teen Accounts Private Meta Child Safety?_Hsenc=P2Anqtz _8Ag1Ousyxq9Xns9Qk4Kybes Tlgnboyjqqxn5Xaomutu2Qxg74Fykopmk1Vl6Jdy5Xgqd',
 'Instagram Teen Accounts Private Meta Child Safety?_Hsenc=P2Anqtz _Uqy58Vgb0Fis2Ojyxit8Ddacvqhpukj3Jfaywhx8Jkwwyk2Zfgkbldu4Xi5Ufo9Cst0Ho',
 'Instagram Teen Accounts Private Meta Child Safety?_Hsenc=P2Anqtz 8Zvk Llmup_Fa Vbnnm6Ocgi_Dzrnqjwbb4Ohhidabwoqzj6E34Ic4Qzdf3Nugwh1Dc2Tr',
 'Instagram Teen Accounts Private Meta Child Safety?_Hsenc=P2Anqtz  Jjslx12A R572Ogoahs7Wq4Fh99Stmvfsrgykp0Vjo Jcbsfvodmsdg9Lkw8Luxk4Suh1',
 'Instagram Teen Accounts Private Meta Child Safety?_Hsenc=P2Anqtz  Khki3Cr1Mxiyh2W9Bvgnvnsiyn5G51Rmq7Ofwnyxh1Vgiwy6Jib Rey Qszpkelv6Bx7Q',
 '2024 Improve Credit Score Guide',
 'C62421Le4J6O',
 'Yemens Houthis File Hypersonic Missile At Israel What To Know',
 'Israels War On Gaza Live Dozens More Killed Amid Anger Over School Attack',
 'How Did Hezbollahs Pagers Explode In Lebanon',
 'Russia Ukraine War List Of Key Events Day 936',
 'More Than 70 Killed In Mali Attack What Happened Why It Matters',
 'Ten Maps To Understand The Occupied West Bank',
 'Israels War On Gaza Live Lebanon On Edge As New Blasts Kill 20 Wound 450',
 'Chk_Exploding Pagers Psychological Warfare Israels Attack On Hezbollah',
 'Missile Fired From Yemen Lands In Israel Setting Off Sirens Military Says',
 'Israel Will Become A Pariah Over Gaza Genocide Un Rights Experts Say',
 'How A Bangladesh Minister Spent More Than 500M On Luxury Property',
 'Uae Says It Will Not Back Post War Gaza Plans Without Palestinian State',
 'Unga Resolution Against Palestine Occupation Will It Change Anything',
 'Dr Congo Military Court Sentences 37 To Death In Coup Trial',
 'Hezbollah And Israel A Timeline Of Conflict',
 'How Did Hezbollah Get The Pagers That Exploded In Lebanon',
 'Us Accuses Rt Of Covert Intelligence Activities Issues Fresh Sanctions',
 'Why Does The Israeli Army Get Away With Killing Foreign Activists',
 'Russia Ukraine War Live News Kyiv Source Says Arms Depot Hit In Russia',
 'What Challenges Will Algerian President Tebboune Face In His Second Term',
 'European Union Risks Sad Bad Future 2024 09 16',
 'Kremlin Alleged Trump Shooters Ukrainian Links Playing With Fire Has 2024 09 16',
 'More Uk Employers Plan Reduced Pay Increases 2025 Idr Survey Shows 2024 09 19',
 'Fed Bowmans Dissent Is First Fed Governor Since 2005 2024 09 18',
 'Which Hezbollah Hamas Leaders Have Been Assassinated 2024 09 18',
 'Constellation Inks Power Supply Deal With Microsoft 2024 09 20',
 'Citigroup Sells Trust Services Unit Jtc 80 Million 2024 09 16',
 'Headline Saying Abc Moderators Fired Over Presidential Debate Started Satire 2024 09 20',
 '?User_Email=53B2F9B11Bfbe9B5F4A4Bc2Cf4145Ad7Ce31Eb0C539108B66C881F6796172C4F&Lctg=66E400Ca4625Fe2Dff09C173',
 'Volodymyr Zelenskyy Ukraine Europe Russia War Media',
 'Viktor Orban Hungary Germany Finally Waking Up Migration Consequences Border Protection Control',
 'The Winners And Losers Of The New European Commission',
 'Kursk Russia Incursion Objections War In Ukraine Volodymyr Zelenskyy',
 'New Eu Defense Commissioner All In On Supporting Ukraine',
 'Serbia President Aleksandar Vucic Kosovo Prime Minister Albin Kurti Eu Talks',
 'Eu Country Vote On Chinese Ev Duties Delayed',
 'Eu Georgia Visa Free Access Schengen Zone Democratic Backsliding',
 'Europe Enlargement Slovenia Marta Kos Russia Ukraine Moldova Accession',
 'Eu Power Structure Ursula Von Der Leyen Team',
 'Eu Dodging Plastic Tax Court Auditors',
 'Ursula Von Der Leyen New European Commission Portfolio',
 'Eu Forms Tech Investor Club High Risk Ventures Mario Draghi',
 'Intel Germany Chips Plant Competitiveness Eu Ambition',
 'European Parliament Venezuela Exil Edmundo Gonzalez Legitimate President',
 'Latvian Veteran Valdis Dombrovskis Eu Economy Commissioner Germany Spending Rules',
 'Steady Hands Sefcovic Is The Surprise Pick For Eu Trade Czar',
 'Former Poland Prime Minister Mateusz Morawiecki Environmentalism Reindustrialization Economy Industry Green Policy Competitiveness',
 'Donald Trump Europe Ally Defense Fbi Probe Attempted Assassination Viktor Orban Matteo Salvini',
 'Oliver Varhelyi Hungary Viktor Orban Brussels Health',
 'Lithuanias Andrius Kubilius Named Defense And Space Commissioner',
 'India Prime Minister Narendra Modi Red Sea Shipping Attacks Houthis Greek Tanker Sounion Eunavfor Aspides',
 'De Reine A Imperatrice Dans Les Coulisses De La Prise De Pouvoir Dursula Von Der Leyen',
 'Russia Stage Violent Coup Armenia Investigation Allegiation',
 'Police Ghost Encryption App Drug Lords Mafia Europol',
 'Freedom Exile Russia Prisoner Swap Sasha Skochilenko Vadim Krasikov Evan Gershkovich',
 'Worlds Cartoonists On This Weeks Events 133',
 'Volodymyr Zelenskyy Us President Ukraine Us War',
 'Dragon Bear How China And Russias Spy Operations Overlap In Europe',
 'German Conservative Leader Friedrich Merz Announces Chancellor Candidacy',
 'Spains Ribera Nominated As Commissions First Vp In Charge Of Clean Transition',
 'Ursula Von Der Leyen New Eu Commissioners Nominees Rejected Parliament',
 'Uk Prime Minister Keir Starmer Us President Joe Biden Vladimir Putin Threat War Storm Shadow Missiles Ukraine',
 'Uk Tech Policy 20 People Meet Labour Conference',
 'Israel Pagers Hezbollah Lebanon Health Ministry',
 'Ekaterina Zaharieva',
 'Germanys Scholz Wants New Eu Anti Deforestation Law Delayed',
 'Beginners Guide Ursula Von Der Leyen European Commission Brussels',
 'Nato Russia Ukraine War Jens Stoltenberg',
 'Britain Labour Government France Plan New Military Agreement Defense Secretary John Healey',
 'Europe Next Migration Chief Tennis Hotshot Magnus Brunner Open Champion',
 'Energy Uk',
 'West Funding Vladimir Putin Soldier Russia Fuel Oil Ukraine War',
 'Denmarks Jorgensen Tapped For Top Eu Energy And Housing Job',

In [230]:
# 1. Remove .html/.htm endings
df_featurized["url_slug_title"] = df_featurized["url_slug_title"].str.replace(r"\.html?$", "", case=False, regex=True)

# 2. Expand no_title to include:
#    - known opaque publishers (BBC, NPR)
#    - missing or empty titles
#    - titles with ≤ 1 word
df_featurized["no_title"] = (
    df_featurized["news_org"].isin(["www.bbc.com", "www.npr.org"]) |
    df_featurized["url_slug_title"].isna() |
    (df_featurized["url_slug_title"].str.strip() == "") |
    (df_featurized["url_slug_title"].str.strip().str.split().str.len() <= 1)
)

In [257]:
df_featurized["L_num_title_words"] = df_featurized["url_slug_title"].apply(
    lambda x: len(str(x).strip().split()) if pd.notna(x) else 0
)

In [259]:
df_featurized["L_num_title_words"].max()

np.int64(30)

In [232]:
df_featurized.date

0       2024-09-10
1       2024-09-09
2       2024-09-10
3       2024-09-11
4       2024-09-10
           ...
5998    2025-04-20
5999    2025-04-11
6000    2025-04-16
6001    2025-04-07
6002    2025-04-16
Name: date, Length: 6003, dtype: object

In [233]:
df_featurized[df_featurized["date"].isna()]

,url,datetime,language,description,article_text,source,is_relevant,used_description_as_text,extracted_entities,entity_relationships,...,quote_count,contains_number,capital_ratio,mentions_social_media,article_type,election_keyword_count,triggered_keyword,mentions_election_keywords,election_certainty,no_title
3306,https://www.bbc.com/news/live/ce3qnyr7y94t,NaT,en,Donald Trump says he has no plans to pause glo...,Trump passes on pausing tariffs as global turm...,french,0,0,"{'people': ['Donald Trump', 'Natalie Sherman']...","[{'source': 'Donald Trump', 'target': 'China',...",...,6,True,0.027027,False,other,0,None,False,0,True
3491,https://www.aljazeera.com/where/kosovo,NaT,en,Stay on top of Kosovo latest developments on t...,An escalation into a conflict in the Western B...,french,0,0,"{'people': [], 'institutions': [], 'political_...",[],...,0,False,0.000000,False,other,0,None,False,0,True
3594,https://www.aljazeera.com/where/mexico,NaT,en,Stay on top of Mexico latest developments on t...,Mexican president says she told Donald Trump t...,french,0,0,"{'people': ['Donald Trump'], 'institutions': [...","[{'source': 'Mexico', 'target': 'US army', 're...",...,0,False,0.050000,False,other,0,None,False,0,True
3885,https://www.france24.com/fr/tag/pape-l%C3%A9on...,NaT,fr,Retrouvez toute l'actualité internationale et ...,,french,0,1,"{'people': ['Pape Léon XIV'], 'institutions': ...",[],...,0,False,0.000000,False,other,0,None,False,0,False
4040,https://www.spiegel.de/politik/deutschland/uni...,NaT,de,Union und SPD haben sich auf einen Koalitionsv...,Analyse: Der Koalitionsvertrag und die Klimapo...,german,1,0,"{'people': [], 'institutions': [], 'political_...",[],...,0,True,0.004149,False,other,0,None,False,0,False
4376,https://www.tagesschau.de/thema/livestream,NaT,de,Livestream - Nachrichten und Information: An 3...,Live-Shopping Zu Hause - und doch im Geschäft\...,german,0,0,"{'people': ['Karen Münster'], 'institutions': ...",[],...,0,False,0.000000,False,other,0,None,False,0,True
4766,https://www.faz.net/pro/weltwirtschaft/weltwis...,NaT,de,Über die Verflechtungen mit Deutschland treffe...,FAZ+ Osteuropa : Auch Trumps Freunde leiden un...,german,0,0,"{'people': ['Andreas Mihm', 'Trump'], 'institu...","[{'source': 'Trump', 'target': 'Osteuropa', 'r...",...,0,True,0.019231,False,other,0,None,False,0,False
4787,https://www.faz.net/podcasts/f-a-z-podcast-fue...,NaT,de,Ein Angelteich als Zentrale von Mafia-Drogenku...,"Wir sprechen darüber, wie weit verzweigt die k...",german,0,0,"{'people': ['Daniel Brombacher'], 'institution...",[],...,0,False,0.000000,False,other,0,None,False,0,False
4800,https://www.faz.net/aktuell/reise/maut-in-euro...,NaT,de,Einiges Europa? Von wegen. Die Gebühren für di...,"Ein Pickerl für Österreich, Maut für den Karaw...",german,0,0,"{'people': [], 'institutions': ['EU'], 'politi...",[],...,0,True,0.000000,False,other,0,None,False,0,False
4804,https://www.faz.net/aktuell/fotografie/wildpfe...,NaT,de,In der nordwestspanischen Region Galicien spie...,Wildpferde gegen das Feuer : Galiciens letzte ...,german,0,0,"{'people': [], 'institutions': ['Reuters'], 'p...",[],...,0,True,0.000000,False,other,0,None,False,0,False
4825,https://www.faz.net/aktuell/wirtschaft/unterne...,NaT,de,Chinas Staatschef lädt die mächtigsten Wirtsch...,FAZ+ Techriesen im Fokus : Xi umgarnt sogar Ja...,german,0,0,"{'people': ['Xi Jinping', 'Jack Ma'], 'institu...","[{'source': 'Xi Jinping', 'target': 'Jack Ma',...",...,0,True,0.014925,False,other,0,None,False,0,False
4843,https://www.faz.net/aktuell/politik/sind-deuts...,NaT,de,Auch wenn Boris Pistorius die Berichte aus der...,Panzer nicht kriegstüchtig? : Die Wahrheit übe...,german,0,0,"{'people': ['Boris Pistorius', 'Berthold Kohle...","[{'source': 'Boris Pistorius', 'target': 'Beri...",...,0,True,0.015625,False,other,0,None,False,0,False
4853,https://www.faz.net/pro/weltwirtschaft/sicherh...,NaT,de,"Zugriff auf alle Inhalte inklusive FAZ+ 12,80 ...","Krieg in der Ukraine und im Nahen Osten, immer...",german,0,0,"{'people': [], 'institutions': ['ICAN (Interna...",[],...,0,True,0.013333,False,other,0,None,False,0,False
4858,https://www.faz.net/aktuell/spiele/wie-gut-koe...,NaT,de,Kann und vor allem darf KI auch Kunst? Die akt...,Haben Sie sich in den vergangenen Tagen auch v...,german,0,0,"{'people': [], 'institutions': ['F.A.Z.', 'Ghi...",[],...,4,True,0.036474,False,other,0,None,False,0,False
4866,https://www.faz.net/pro/weltwirtschaft/weltwis...,NaT,de,In Reaktion auf Trumps Zollerhöhungen schlagen...,Nachdem die Amerikaner die Importzölle auf chi...,german,0,0,"{'people': [], 'institutions': [], 'political_...","[{'source': 'USA', 'target': 'China', 'relatio...",...,0,True,0.020408,False,other,0,None,False,0,False
5056,https://www.bbc.com/news/topics/c302m85q5rjt,NaT,en,Human rights journalist Abdalle Mumin spends a...,"Global executions at highest level since 2015,...",german,0,0,"{'people': [], 'institutions': ['Amnesty Inter...","[{'source': 'Amnesty International', 'target':...",...,0,True,0.000000,False,other,0,None,False,0,True

In [237]:
df_featurized.columns

Index(['url', 'datetime', 'language', 'description', 'article_text', 'source',
       'is_relevant', 'used_description_as_text', 'extracted_entities',
       'entity_relationships', 'has_entities', 'has_relationships',
       'has_people', 'has_organizations', 'news_org', 'url_slug_title', 'date',
       'day_of_week', 'month', 'is_weekend', 'days_until_us_election',
       'days_until_french_election', 'days_until_german_election',
       'word_count', 'sentence_count', 'avg_sentence_length', 'noun_count',
       'verb_count', 'contains_question', 'quote_count', 'contains_number',
       'capital_ratio', 'mentions_social_media', 'article_type',
       'election_keyword_count', 'triggered_keyword',
       'mentions_election_keywords', 'election_certainty', 'no_title'],
      dtype='object')

# llm features

In [252]:
import ast

# Total entities
df_featurized["L_n_total_entities"] = df_featurized["extracted_entities"].apply(
    lambda x: sum(len(v) for v in ast.literal_eval(x).values()) if pd.notna(x) else 0
)

# People, Locations, Political Actors, Institutions
df_featurized["L_n_people"] = df_featurized["extracted_entities"].apply(
    lambda x: len(ast.literal_eval(x).get("people", [])) if pd.notna(x) else 0
)
df_featurized["L_n_locations"] = df_featurized["extracted_entities"].apply(
    lambda x: len(ast.literal_eval(x).get("locations", [])) if pd.notna(x) else 0
)
df_featurized["L_n_institutions"] = df_featurized["extracted_entities"].apply(
    lambda x: len(ast.literal_eval(x).get("institutions", [])) if pd.notna(x) else 0
)


# Number of relationships
df_featurized["L_n_relationships"] = df_featurized["entity_relationships"].apply(
    lambda x: len(ast.literal_eval(x)) if pd.notna(x) else 0
)

In [253]:
df_featurized.groupby("is_relevant")[["L_n_total_entities","L_n_people", "L_n_locations", "L_n_institutions",  "L_n_relationships"]].describe().T

is_relevant                         0            1
L_n_total_entities count  4916.000000  1071.000000
                   mean     11.588283    20.641457
                   std      14.255071    26.076170
                   min       0.000000     0.000000
                   25%       3.000000     7.000000
                   50%       8.000000    15.000000
                   75%      16.000000    25.000000
                   max     255.000000   346.000000
L_n_people         count  4916.000000  1071.000000
                   mean      3.098861     6.844071
                   std       6.212381    12.242906
                   min       0.000000     0.000000
                   25%       0.000000     2.000000
                   50%       2.000000     4.000000
                   75%       4.000000     8.000000
                   max     142.000000   195.000000
L_n_locations      count  4916.000000  1071.000000
                   mean      4.193247     5.550887
                   std       5.482506     8.272179
                   min       0.000000     0.000000
                   25%       1.000000     1.000000
                   50%       2.000000     3.000000
                   75%       6.000000     7.000000
                   max     125.000000   115.000000
L_n_institutions   count  4916.000000  1071.000000
                   mean      3.646257     5.366013
                   std       4.628011     7.202578
                   min       0.000000     0.000000
                   25%       1.000000     2.000000
                   50%       2.000000     4.000000
                   75%       5.000000     7.000000
                   max      69.000000   158.000000
L_n_relationships  count  4916.000000  1071.000000
                   mean      2.978234     5.500467
                   std       4.362717     5.702742
                   min       0.000000     0.000000
                   25%       0.000000     1.000000
                   50%       1.000000     4.000000
                   75%       4.000000     8.000000
                   max      60.000000    72.000000

In [260]:
df_featurized["L_named_entity_density"] = df_featurized.apply(
    lambda row: (
        row["L_n_total_entities"] / len(str(
            row["article_text"] if pd.notna(row["article_text"]) and not row.get("used_description_as_text", 0)
            else row.get("description", "")
        ).split())
        if len(str(row["article_text"] if pd.notna(row["article_text"]) else row.get("description", "")).split()) > 0
        else 0
    ),
    axis=1
)

In [263]:
df_featurized.groupby("is_relevant")["L_named_entity_density"].describe()

,count,mean,std,min,25%,50%,75%,max
is_relevant,,,,,,,,
0,4916.0,0.031915,0.035713,0.0,0.000000,0.027027,0.043773,0.558824
1,1071.0,0.035156,0.027753,0.0,0.019538,0.028944,0.043421,0.198473

In [264]:
df_featurized["L_avg_sentiment_polarity"] = df_featurized["entity_relationships"].apply(
    lambda x: (
        np.mean([
            {"friendly": 1, "neutral": 0, "hostile": -1}.get(r.get("sentiment", "neutral").lower(), 0)
            for r in ast.literal_eval(x)
        ]) if pd.notna(x) and isinstance(ast.literal_eval(x), list) and len(ast.literal_eval(x)) > 0
        else 0
    )
)

In [265]:
df_featurized["L_avg_sentiment_polarity"].describe()

count    5987.000000
mean       -0.190431
std         0.395155
min        -1.000000
25%        -0.400000
50%         0.000000
75%         0.000000
max         1.000000
Name: L_avg_sentiment_polarity, dtype: float64

# encriching data set with publisher metadata

# saving to csv

In [270]:
df_featurized.to_csv("data.csv")

In [269]:
df_featurized.news_org.value_counts()

news_org
www.aljazeera.com         663
www.politico.eu           641
www.euronews.com          590
www.france24.com          482
www.bbc.com               420
www.reuters.com           383
www.nbcnews.com           254
www.npr.org               218
www.cnn.com               209
www.liberation.fr         170
www.nytimes.com           170
www.zeit.de               170
www.lefigaro.fr           170
www.sueddeutsche.de       170
www.tagesschau.de         169
www.bild.de               169
www.rfi.fr                169
www.bfmtv.com             169
www.spiegel.de            169
www.lemonde.fr            168
www.faz.net               161
www.washingtonpost.com     66
www.bloomberg.com          18
apnews.com                 12
observers.france24.com      4
france24.com                2
www.theguardian.com         1
Name: count, dtype: int64

In [272]:
df_featurized.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5987 entries, 0 to 5986
Data columns (total 47 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   url                         5987 non-null   object
 1   datetime                    5987 non-null   datetime64[ns]
 2   language                    5987 non-null   object
 3   description                 5987 non-null   object
 4   article_text                5983 non-null   object
 5   source                      5987 non-null   object
 6   is_relevant                 5987 non-null   Int64
 7   used_description_as_text    5987 non-null   int64
 8   extracted_entities          5987 non-null   object
 9   entity_relationships        5987 non-null   object
 10  has_entities                5987 non-null   int64
 11  has_relationships           5987 non-null   int64
 12  has_people                  5987 non-null   int64
 13  has_organizations           5987 non-null   int64
 14  news_org                    5987 non-null   object
 15  url_slug_title              5987 non-null   object
 16  date                        5987 non-null   object
 17  day_of_week                 5987 non-null   object
 18  month                       5987 non-null   float64
 19  is_weekend                  5987 non-null   bool
 20  days_until_us_election      5987 non-null   float64
 21  days_until_french_election  5987 non-null   float64
 22  days_until_german_election  5987 non-null   float64
 23  word_count                  5987 non-null   int64
 24  sentence_count              5987 non-null   int64
 25  avg_sentence_length         5987 non-null   float64
 26  noun_count                  5987 non-null   int64
 27  verb_count                  5987 non-null   int64
 28  contains_question           5987 non-null   bool
 29  quote_count                 5987 non-null   int64
 30  contains_number             5987 non-null   bool
 31  capital_ratio               5987 non-null   float64
 32  mentions_social_media       5987 non-null   bool
 33  article_type                5987 non-null   object
 34  election_keyword_count      5987 non-null   int64
 35  triggered_keyword           551 non-null    object
 36  mentions_election_keywords  5987 non-null   bool
 37  election_certainty          5987 non-null   int64
 38  no_title                    5987 non-null   bool
 39  L_n_total_entities          5987 non-null   int64
 40  L_n_people                  5987 non-null   int64
 41  L_n_locations               5987 non-null   int64
 42  L_n_relationships           5987 non-null   int64
 43  L_n_institutions            5987 non-null   int64
 44  L_num_title_words           5987 non-null   int64
 45  L_named_entity_density      5987 non-null   float64
 46  L_avg_sentiment_polarity    5987 non-null   float64
dtypes: Int64(1), bool(6), datetime64[ns](1), float64(8), int64(18), object(13)
memory usage: 1.9+ MB